worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" upstream=$upstream_addr';

    access_log /logs/access.log main;

    upstream backend {
        server host.docker.internal:5001 max_fails=2 fail_timeout=5s;
        server host.docker.internal:5002 max_fails=2 fail_timeout=5s;

        # по очереди
        # least_conn; кто свободнее
        # ip_hash; по апи выбирает нужный сервер обычно тот же
        # хэш по параметру
        # веса
    }

    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_next_upstream error timeout http_502 http_503 http_504;

            # чтобы видеть, какой backend ответил
            add_header X-Upstream $upstream_addr always;
        }
    }
}