worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;

    access_log /dev/stdout;
    error_log /dev/stderr;

    upstream backend {
        server host.docker.internal:5001 max_fails=2 fail_timeout=5s;
        server host.docker.internal:5002 max_fails=2 fail_timeout=5s;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://backend;

            proxy_http_version 1.1;

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;

            add_header X-Upstream $upstream_addr always;
        }
    }
}